#!/bin/busybox sh

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
 
# Populate /dev
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# Wait for card?
sleep 5

# Create mounting locations and overlay things.
mkdir -p /mnt/root-ro
mount -o ro /dev/mmcblk0p2 /mnt/root-ro

mkdir -p /mnt/root-rw
mount -t tmpfs tmpfs /mnt/root-rw
mkdir /mnt/root-rw/upper
mkdir /mnt/root-rw/work

mkdir -p /rootfs
mount -t overlay overlay -o lowerdir=/mnt/root-ro,upperdir=/mnt/root-rw/upper,workdir=/mnt/root-rw/work /rootfs
 
# Move mounts
mount --move /mnt/root-ro /rootfs/mnt/root-ro
mount --move /mnt/root-rw /rootfs/mnt/root-rw

mount -t devtmpfs devtmpfs /rootfs/dev

# Clean up.
umount /proc
umount /sys

exec switch_root /rootfs /bin/busybox init
