#!/bin/sh
# -*- mode: sh -*-

source /etc/private/private.env

while /bin/true; do
    ssh -i /etc/private/tunnel.id_rsa.dropbear -y -N -R ${SSH_TUNNEL_PORT}:127.0.0.1:22 ${SSH_TUNNEL_END} 2>&1 | /usr/bin/logger -t ssh-tunnel
    sleep 10
done
