#!/bin/sh
# -*- mode: sh -*-

NAME=data-partition

# Read config file if it is present.
if [ -r /etc/default/$NAME ]; then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    printf "Starting $NAME: "
    /bin/create-data-partition.sh
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
