#!/bin/sh
# -*- mode: sh -*-
#
# Very aggressive outside connection startup.
#

NAME=network-watcher

# Read config file if it is present.
if [ -r /etc/default/$NAME ]; then
  . /etc/default/$NAME
fi

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
        printf "Starting network-watcher: "
        start-stop-daemon -S -q -b --startas /bin/bash -- -c "exec /usr/local/bin/network-watcher 2>&1 | /usr/bin/logger -t network-watcher 2>&1"
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop  )
        printf "Stopping network-watcher: "
        start-stop-daemon -K -q -n $NAME
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
