#!/bin/sh
# -*- mode: sh -*-
#

NAME=fake-hwclock

# Read config file if it is present.
if [ -r /etc/default/$NAME ]; then
  . /etc/default/$NAME
fi

case "$1" in
  start)
        printf "Starting $NAME: "
        /bin/fake-hwclock load
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop  )
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
